### PR TITLE
Laravel7 compatibility

### PR DESCRIPTION
**Pull request by lenssoft**
This PR adds compatibility to laravel ^7 (probably earlier versions too).

@mruoss could you make a new version tag (e.g. 7.0.0) out of this changes and possibly update the README about which versions to include based on laravel version.

### CODE REVIEW

**Comment by mruoss** [comment]
Hi @lenssoft 

Unfortunately, I am not maintaining this module actively anymore. Would you be willing to take it over?

**Comment by lenssoft** [comment]
If i am going to use it in production then I will be able to take over. Until then I can use my forked repo with the compatibility fix.

**Comment by mruoss** [comment]
ok let me know.

**Comment by lenssoft** [comment]
Hi @mruoss 
We decided to use this package in production. Could you add me as a maintainer to the repo?

**Comment by mruoss** [comment]
Done. Let me know your packagist username if you want to deploy there.

**Comment by lenssoft** [comment]
My packagist username is lenssoft

**Comment by mruoss** [comment]
Also by the way, it seems like this project was forked and re-published already: https://github.com/highsolutions/laravel-lang-import-export

**Comment by lenssoft** [comment]
good to know

**Comment by mruoss** [comment]
Yeah, since I was not maintaining it, this makes sense. It is also has more downloads than my original one and is maintained. So feel free to re-create a pull request also on their side and maybe at some point we can close this project. Up to you.

**Comment by mruoss** [comment]
I guess you closed this in favor for https://github.com/highsolutions/laravel-lang-import-export/pull/10?

**Comment by lenssoft** [comment]
I closed this in favour of https://github.com/ufirstgroup/laravel-lang-import-export/pull/6

**Comment by mruoss** [comment]
I see. Thanks.

**Pull request closed without merging**
